global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'apache-exporter'
    static_configs:
      - targets: ['apache-exporter:9117']
  - job_name: 'ejb-exporter'
    static_configs:
      - targets: ['172.17.0.1:7001']
